### ISSUE TITLE
Homebrew commands are out of date

### ISSUE THREAD

**Issue by ishaan26** [m1guelpf/plz-cli#15]
When I asked the plz-cli to install docker on my mac, it threw the following error:
```
❯ plz install docker
✔ Got some code!
────────────────────────────────────────────────────────────────────────────────
# install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install docker
brew cask install docker

# start docker
open /Applications/Docker.app
────────────────────────────────────────────────────────────────────────────────
>> Run the generated program? [Y/n] y
✖ The program threw an error.
Error: The Ruby Homebrew installer is now disabled and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
The file /Applications/Docker.app does not exist.

```
The install command for homebrew is out of date. Further, the brew commands need to be updated to remove the "cask" arguments as those are deprecated.

**Comment by tomturner10** [comment]
plz-cli just calls the open [AI code completion api](https://beta.openai.com/docs/guides/code/introduction), any returned code is from them and could be out of date or wrong.
This is just a limitation of the AI and cant really be solved at the moment without implementing some advanced error checking, probably beyond the scope of this project

**Comment by ishaan26** [comment]
Ahh. I see. I'll close this issue here then. Thanks.
