### ISSUE TITLE
More info for error "Failed to get a response. Have you set the OPENAI_API_KEY variable?"

### ISSUE THREAD

**Issue by dylang** [m1guelpf/plz-cli#2]
Hi, looking forward to trying this, getting an error though and I'm not sure how to debug it. 

The key is freshly made from https://beta.openai.com/account/api-keys. 
I'm using fish shell 3.5.1 in MacOS.

```
 ❯ echo $OPENAI_API_KEY
sk-<key hidden>
 ❯ plz "list files"
✖ Failed to get a response. Have you set the OPENAI_API_KEY variable?
```

I've yet to try to code in Rust so I'm not set up to try to modify the source and see what's happening.

**Comment by yorhodes** [comment]
have the same issue @m1guelpf

**Comment by omeb** [comment]
Having the same issue as well...
![image](https://user-images.githubusercontent.com/7505578/207735512-4b8036b3-fbda-4999-8fb8-a6bf776234d4.png)

**Comment by raulsanzmontrull** [comment]
Same here (KDE Neon). Also having OPENAI_API_KEY variable persisted
<edit>
I think that it does not depend on setting `OPENAI_API_KEY` variable because plz do not let you run a request to OPENAI API without KEY variable.  It shows the next message:
`This program requires an OpenAI API key to run. Please set the OPENAI_API_KEY environment variable.`
IDK if it is related to API permissions or whatever. 
</edit>

**Comment by jcortejoso** [comment]
I had problems with API_KEYS from my personal account as my account had not enough credit to make any request. You can confirm if you are able to make requests at https://beta.openai.com/playground (just make a dummy request there).

<blockquote><img src="https://beta.openai.com/curl.png" width="48" align="right"><div><strong><a href="https://beta.openai.com">OpenAI API</a></strong></div><div>An API for accessing new AI models developed by OpenAI</div></blockquote>

**Comment by ghost** [comment]
Having the same issue here

**Comment by raulsanzmontrull** [comment]
I tried to provide billing details and set my credit card at OpenAI. Then, I repeated the steps and it worked for me:

![image](https://user-images.githubusercontent.com/50600011/207823226-2e118dbe-59f0-4323-9d8a-dc4fbbe4b334.png)

<edit> Thanks to @jcortejoso for the message! </edit>

**Comment by m1guelpf** [comment]
Would be really helpful if anyone experiencing this issue could share a copy of the response returned, so I can improve the error message on the CLI

**Comment by markkucler** [comment]
I had the same problem, billing/playground showed "You've reached your usage limit." and it started working once I provided billing details. Thanks @jcortejoso and @llunasanz!

**Comment by yorhodes** [comment]
also was just a billing issue for me

**Comment by bwagner** [comment]
I've set up billing, confirmed that the playground works, still get the error message:
`✖ Failed to get a response. Have you set the OPENAI_API_KEY variable?`
