### ISSUE TITLE
Temp files

### ISSUE THREAD

**Issue by arthurmelton** [m1guelpf/plz-cli#3]
Why is a temporary file being made when you could just make a file only if the user asks for it. If you want to run a bash script and have the code you could do 
```sh
bash -c "echo hi"
```
in rust it would be
```rs
Command::new("bash")
            .arg("-c")
            .arg(my_cool_code_variable)
```
This supports everything a bash script would allow just make sure its all as one argument.

**Comment by m1guelpf** [comment]
Didn't know this was possible, thanks for the idea!
