### ISSUE TITLE
Fix build scripts on Linux

### ISSUE THREAD

**Issue by igorrhamon** [m1guelpf/plz-cli#4]
Trying to use plz on Ubuntu WSL.
During the installation, the same error occurred.

"error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory"

**Comment by m1guelpf** [comment]
Are you building from scratch, or using one of the provided binaries?

**Comment by noobosaurus-r3x** [comment]
using :
curl -fsSL https://raw.githubusercontent.com/m1guelpf/plz-cli/main/install.sh | sh -
on Debian, I receive the same error message

**Comment by maximofn** [comment]
I have the same problem, i use
```
curl -fsSL https://raw.githubusercontent.com/m1guelpf/plz-cli/main/install.sh | sh -
```
on Ubuntu 20.04 and get same error

**Comment by BinaryFox83** [comment]
Same error on wsl2

**Comment by bjoern247** [comment]
Same error for me on Ubuntu 20.04

**Comment by m1guelpf** [comment]
hmm, seems like the way we build the binary might be broken for linux. Would love a PR to address this (since I'm not an expert on building Rust for Linux)

**Comment by culda** [comment]
FYI I'm on Ubuntu 22.10 and it works perfectly. 
The only tiny issue is executing with the `sh` doesn't like the `[[ ]]` syntax (I think because of zshell, but not sure).
But if you execute the script directly with the `./` prefix, no errors

**Comment by jadonbrownza** [comment]
> FYI I'm on Ubuntu 22.10 and it works perfectly. The only tiny issue is executing with the `sh` doesn't like the `[[ ]]` syntax (I think because of zshell, but not sure). But if you execute the script directly with the `./` prefix, no errors

Are you referring to the install script?
I'm trying to run it directly by running `./install.sh` but the error still persists:
![image](https://user-images.githubusercontent.com/7773361/208305118-6225abd1-cb9e-4b75-9f35-51b4e19c18fa.png)

`/.bin/plz: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
installed -`

**Comment by culda** [comment]
@scheMeZa You need to have `libssl-dev` installed, and then you need an env `LD_LIBRARY_PATH` pointed at the `lib` folder. It's a typical issue you'll find details on google if you get stuck.
I used brew so mine is `/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1s/lib`

**Comment by 0xempire** [comment]
### issue

The actual problem derives from the feature `default-tls` of [reqwest](https://github.com/seanmonstar/reqwest#requirements), that has [openssl-sys](https://github.com/sfackler/rust-openssl/blob/ea18d84de3ff5a6bc374fb954f05a8629648a37e/openssl-sys/build/main.rs#L186) as underlying dep  thus the compiled binary will look for `libssl.so.3` installed in Linux.

![bin-rustls-tls](https://user-images.githubusercontent.com/108901272/208314273-22444378-7572-4174-b6a6-d18a9f046208.png)

### solution(s)
In a scalable solution users shouldn't have to install anything additional:
a) You can try to compile the deps in the bin either with `rustls-tls` as below, or bundling with "vendored" openssl. 
b) Use another HTTP client if you encounter [speed issues](https://github.com/seanmonstar/reqwest/issues/1454) in the benchmarks e.g. hyper/ureq/other always keeping in mind that any lib depending on [rust-native-tls](https://github.com/sfackler/rust-native-tls) will have the same issue.

![bin-rustls-tls](https://user-images.githubusercontent.com/108901272/208314497-2d57d3b1-b175-4d46-962b-c73126b27573.png)

```toml
# Cargo.toml
# ...
reqwest = { version = "0.11.13", default-features = false, features = ["json", "blocking", "rustls-tls"] }
```

rustls-tls bin size diff: +2.1MB

**Comment by m1guelpf** [comment]
Should be fixed in the newest release
